# Generated by Django 2.0.1 on 2020-03-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dob',
            field=models.DateField(),
        ),
    ]
