# Generated by Django 2.0.1 on 2020-03-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20200314_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_location', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=50)),
                ('driver_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
            ],
        ),
    ]
