# Generated by Django 2.0.1 on 2020-05-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='aadhar_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
