# Generated by Django 2.0.1 on 2020-05-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20200507_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='aadhar_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
