# Generated by Django 2.0.1 on 2020-05-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20200507_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='Back_view',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='Front_view',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='Side_view_1',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='Side_view_2',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
