# Generated by Django 2.0.1 on 2020-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20200507_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_license_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
