# Generated by Django 2.0.1 on 2020-05-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_driver_driving_license_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='rc_no',
        ),
    ]
