# Generated by Django 2.0.1 on 2020-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('h_loc', models.CharField(max_length=100)),
                ('h_mobile', models.CharField(max_length=100)),
            ],
        ),
    ]
