# Generated by Django 2.0.1 on 2020-03-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoordinates',
            name='pick_status',
            field=models.BooleanField(default=False),
        ),
    ]
