# Generated by Django 2.0.1 on 2020-03-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_ambulance'),
        ('user', '0003_usercoordinates_pick_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoordinates',
            name='driver_picked',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
    ]
