# Generated by Django 2.0.1 on 2020-04-15 05:21

from django.db import migrations, models
from driver.models import *

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200415_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoordinates',
            name='driver_picked',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
