# Generated by Django 2.0.1 on 2020-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usercoordinates_driver_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoordinates',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
